"""${message}

TODO: replace the line above with a docstring saying *why* this change is
needed -- the "what" is already visible in the code below.

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

When editing this file, remember:

- Autogenerated output is a draft. Delete anything that was not intended;
  spurious type diffs are common.
- Never import the ORM models. This revision must keep meaning the same
  schema forever, and the models move. Use string table/column names.
- Prefer a single DDL statement. MySQL commits implicitly on DDL, so a
  multi-statement revision cannot be rolled back there; split it instead.
- Make it idempotent, by inspection rather than by ``IF NOT EXISTS``
  (which MySQL 8 does not accept for indexes). For the same reason as
  above, a crash can leave the change applied but this revision
  unrecorded, and the re-run has to succeed. See
  ``0002_image_session_index.py`` for the shape.
- Add this file to ``versions/meson.build`` or it will be missing from
  installed builds.
"""

import alembic
import sqlalchemy
${imports if imports else ""}

# revision identifiers, used by Alembic.
revision = ${repr(up_revision)}
down_revision = ${repr(down_revision)}
branch_labels = ${repr(branch_labels)}
depends_on = ${repr(depends_on)}


def upgrade():
    """Apply the change."""

    ${upgrades if upgrades else "pass"}


def downgrade():
    """Revert the change."""

    ${downgrades if downgrades else "pass"}
