# Generated by Django 5.0.2 on 2026-08-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiagnosticExpression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the record was created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When the record was last changed",
                    ),
                ),
                (
                    "name",
                    models.SlugField(
                        help_text="Name shown in the diagnostics selectors",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "expression",
                    models.TextField(
                        help_text="Python expression over per-image diagnostic names"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="What the expression is for"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
