# Generated by Django 6.1 on 2026-09-25 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diagnostics", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DiagnosticExpression",
        ),
    ]
