# Generated by Django 5.0.2 on 2026-08-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, help_text="When the record was last changed"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When the record was created"
            ),
        ),
    ]
