src = [
  'floating_params.css',
  'jquery.orgchart.css',
  'logs.css',
  'progress_bar.css',
  'select_images.css',
  'select_photref.css',
  'checkboxes.css',
  'tune_starfind.css'
]

py.install_sources(
    src,
    subdir: 'autowisp/browser_interface/processing/static/processing/css',
    pure: true,
)
